- rust/emitter/src/ast_emitter.rs
- rust/emitter/src/emitter.rs
- rust/emitter/src/lib.rs
Changed fallible emitter functions to return `Result<EmitResult, EmitError>` or `Result<(), EmitError>`,
and replaced `unimplemented!()` with `return Err(EmitError::Unimplemented("...".to_string()));`
Corresponding change to rust-frontend will use the result to report unimplemented error to the API consumer.
> Add EmitError::Unimplemented to report unimplemented error

- rust/parser/src/lexer.rs
This PR fix the lexer to correctly reject inputs such as:
```js
// Bug 1319415
var src =
`(modu
```
> Fix template strings end and escape sequences.

- rust/generated_parser/src/error.rs
- rust/parser/src/lexer.rs
Tested and works locally.
Do we have a place for adding non-parsing test cases?
> Fix #22 - Reject non-ending multiline comments.

- rust/parser/src/lexer.rs
The following test case fails while unwrapping the content of the template string.
```js
Reflect.parse(`
let a
f2()
`);
```
This patch replace the `None` result, by the content produced while iterating over the template string content, using the `builder` initialized earlier.
> Template strings part should return the matching text.

- rust/parser/src/lexer.rs
The following regexp was incorrectly accepted by jsparagus, because the flags of the regexp were not tested against the accepted list of flags.
Here a small test case which should fail.
```js
/ |/ji
```
> (12.2.8.2.2) Throw an error if any non-valid RegExp flag is present.

- rust/generated_parser/src/ast_builder.rs
This is probably badly handled, as we should probably be adding a new enumerated error kind, and also properly report the error location on the corresponding identifier. However, it does address the issue detected while fuzzing.
The problem encountered here, is that `LetOrConst` is not part of the `BindingList` and `LexicalDeclaration` productions, and as such checking whether we are in the `const` case of `LetOrConst` while synthesizing the `LexicalDeclaration` is not yet possible.
In this case, a proper solution would be to add variable to implement left-to-right attribute of an attribute grammar. In the current implementation left-to-right attributes are easy to implement if we restrict our-selfs to only mutate left-to-right attributes while synthesizing productions.
> Fix #44 - Return NotImplemented errors for missing initializers in lexical declarations.

- rust/ast/generate_ast.py
- rust/ast/src/source_location_accessor.rs
- rust/ast/src/types.rs
- rust/ast/src/visit.rs
- rust/emitter/src/ast_emitter.rs
- rust/emitter/src/emitter.rs
- rust/emitter/src/opcode.rs
- rust/generated_parser/src/ast_builder.rs
In the previous change I used `Var(SourceLocation)` etc for the case the enum has no field, but now I think it's better to be consistent with other cases, so changed to `Var { loc: SourceLocation }`
> Consistently use loc field for all types.

- tests/test_js.py
The string was added here when location information was added to the Rust parser. (It would be kind of nice to get location information in the Python parser too, but low priority.)
> Update test expectations. Fixes #62.

- rust/parser/src/lexer.rs
Added `AutoCow::finish_without_push` that excludes the current character when no modification happened,
and used it for string cases.
> Do not include the not-yet-pushed character when finishing AutoCow for string literal (fixes #35)

- rust/emitter/src/ast_emitter.rs
- rust/generated_parser/src/ast_builder.rs
- rust/generated_parser/src/parser_tables_generated.rs
- rust/parser/src/lexer.rs
Numeric separator is parsed and included in the token value.
`AstBuilder::numeric_literal_value` is updated to throw `NotImplemented` when it fails to parse.
> Handle Numeric Separators in lexer, and throw NotImplemented in AstBuilder (fixes #74)

- rust/emitter/src/ast_emitter.rs
- rust/emitter/src/emitter.rs
- rust/emitter/src/lib.rs
- rust/parser/src/lexer.rs
- rust/parser/src/tests.rs
- test.sh
Consists of multiple changesets for each issue.
There's one change for non-test, that is about `LegacyOctalIntegerLiteral`, that was rejecting more than necessity (the troublesome case is only when digit appears after 0).
for `NotImplemented` case, I've added test that checks the `NotImplemented` error is thrown,
so that once it gets fixed, the test will catch it and we can update the test.
> Test fix (fixes #95)

- rust/parser/src/lib.rs
I am not sure if this stuff was hanging around for a specific reason, but this fixes the following two warnings: 
```
warning: unused imports: `Write`, `self`
--> parser/src/lib.rs:20:15
|
20 | use std::io::{self, Write};
|               ^^^^  ^^^^^
|
= note: `#[warn(unused_imports)]` on by default
warning: method is never used: `can_close`
--> parser/src/parser.rs:211:5
|
211 |     pub fn can_close(&self) -> bool {
|     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
|
= note: `#[warn(dead_code)]` on by default
```
> fix rust warnings

- rust/parser/src/lib.rs
reverts https://github.com/mozilla-spidermonkey/jsparagus/pull/111
that conflicted with https://github.com/mozilla-spidermonkey/jsparagus/pull/106
(sorry I overlooked)
> Add back use std::io::{self, Write}

- js_parser/es-simplified.esgrammar
- rust/generated_parser/src/ast_builder.rs
- rust/generated_parser/src/parser_tables_generated.rs
one issue was that `for_*_statement_lexical` wasn't called.
another issue was that `for_declaration` wasn't marking binding.
> Fix Early Errors handling for lexical-for (fixes #124)

- rust/Cargo.lock
- rust/Cargo.toml
- rust/driver/Cargo.toml
- rust/driver/src/demo.rs
- rust/emitter/src/lib.rs
- rust/interpreter/Cargo.toml
- rust/interpreter/src/evaluate.rs
- rust/interpreter/src/lib.rs
- rust/interpreter/src/value.rs
We don't yet emit many opcodes, so this actually has pretty good coverage. 
I think we might soon need a small refactoring to implement something like `read_int8`, `read_int32` for the Opcode bytecode operands.
I made sure that we don't unnecessarily panic, so this is relatively robust when implementing new opcodes.
> Simple bytecode interpreter

- rust/generated_parser/src/ast_builder.rs
- rust/generated_parser/src/error.rs
- rust/generated_parser/src/parser_tables_generated.rs
might be better moving all (new and existing) early errors related code to early_errors.rs tho,
putting into ast_builder.rs for now, given this isn't necessary to be a context, just a single call without depending on the context (while other things in early_errors.rs are context)
> Implement Early Error for labelled function in single statement context (fixes #136)

- rust/parser/src/lexer.rs
The code `a=>{} \n /x/;` involves both ASI and slashes.
The spec language about ASI says that after parsing without ASI fails,
we reparse it as `a=>{}; /x/;`, which succeeds.
This example is subtle because, going by the spec, we would initially
parse the first slash as division. ("In all other contexts,
InputElementDiv is used..."[1]) But after ASI, it is a RegExp. Before
this patch, we do in fact scan it as division and we then fail to
reinterpret it as a RegExp after ASI.
We could fix this by making the lexer rescan the token after doing
ASI. But that is awkward and seems unnecessary. Instead, in places where
neither DivPunctuator nor RegularExpressionLiteral is permitted, choose
RegularExpressionLiteral. Either ASI will happen (and a division
operator is never legal immediately …
> Support RegExp after ASI. Fixes #137.

- rust/generated_parser/src/ast_builder.rs
- rust/generated_parser/src/early_errors.rs
- rust/generated_parser/src/error.rs
- rust/generated_parser/src/parser_tables_generated.rs
Implemented in the same way as duplicate error.
Now `IdentifierEarlyErrorsContext` doesn't contain any field except phantom for lifetime parameter.
but it will hold something to get strict mode, and also the goal (whether it's Module or not).
as mentioned in https://github.com/mozilla-spidermonkey/jsparagus/issues/116 , this doesn't solve
yield/await for `LabelIdentifier` and `IdentifierReference`, given we don't yet have parameter.
Early Errors for `Identifier` are handled at the same time for the encloding non-terminal (`BindingIdentifier` etc), internally.
> Implement Early Error for Identifier (fixes #113)

- rust/interpreter/src/evaluate.rs
- rust/parser/src/lexer.rs
Given parser cannot handle yield/await token properly at this point, I think the quick and less-change fix is just to return NotImplemented from lexer.
This will affect the case when they're used for IdentifierName, but I think that's not much problem.
> Throw NotImplemented when lexer found yield and await (fixes #116)

- rust/interpreter/src/evaluate.rs
- rust/interpreter/src/value.rs
I am not sure what the recommended way in Rust to implement to_boolean and to_number.
Should we make JSValue copyable, or change those methodes to take references?
> Implement And, Or, and Coalesce in the interpreter

- rust/Cargo.lock
- rust/parser/Cargo.toml
- rust/parser/src/lexer.rs
Adds the following dependency:
* unic-ucd-ident
* unic-char-property
* unic-char-range
* unic-common
* unic-ucd-version
all of them are licensed with MIT/Apache-2.0
* https://crates.io/crates/unic-ucd-ident
* https://crates.io/crates/unic-char-property
* https://crates.io/crates/unic-char-range
* https://crates.io/crates/unic-common
* https://crates.io/crates/unic-ucd-version
after merging this, rust-frontend needs `./mach vendor rust` to build.
> Support Unicode identifiers (fixes #130)

- rust/ast/ast.json
- rust/ast/src/source_location_accessor_generated.rs
- rust/ast/src/types_generated.rs
- rust/ast/src/visit_generated.rs
- rust/emitter/src/ast_emitter.rs
- rust/generated_parser/src/ast_builder.rs
- rust/generated_parser/src/stack_value_generated.rs
Refactor `CallExpression` so that it can be reused in optionalChain
> Refactor Call Expression for reusability

- rust/parser/Cargo.toml
- rust/parser/src/lexer.rs
- rust/parser/src/tests.rs
given the spec mentions ID_Start/ID_Continue, using `is_id_start`/`is_id_continue` should be fine?
https://tc39.es/ecma262/#prod-UnicodeIDStart
> Use ID_Start/ID_Continue instead of XID_Start/XID_Continue (fixes #160)

- rust/parser/src/lexer.rs
In non-strict code, these are two-character strings, a null character
followed by an ASCII digit. In strict code, they're SyntaxErrors.
> Return Err(NotImplemented) for '\08' and '\09'. Fixes #161.

- rust/parser/src/lexer.rs
- rust/parser/src/tests.rs
Just like "await" and "yield", now lexer returns NotImplemented immediately when it hit them.
Tests that check "async" and "let" are commented out, with `assert_not_implemented`.
Other tests that were using "let" were rewritten with "const".
> Return NotImplemented for "let" and "async" in lexer (fixes #134)

- jsparagus/emit/rust.py
To support update.sh usage, made `handler_info` optional.
> Report warning when handler_info is not passed, and forcibly generate parser (fixes #152)

- rust/emitter/src/ast_emitter.rs
- rust/interpreter/src/evaluate.rs
- rust/interpreter/src/lib.rs
- rust/interpreter/src/object.rs
- rust/interpreter/src/value.rs
This adds supports for strings and objects, especially a "global" object. We can also read and assign global properties. The global native function `print` can be called.
> Support strings, objects, native function and assignments.

- Makefile
- jsparagus/emit/collect_handler_info/src/main.rs
Now the file is created/updated only when ast_builder.rs is parsed correctly.
So, if there's info.json for previous build and new syntax error is added to ast_builder.rs,
the build process always stops there
(without this patch, info.json was created regardless of the error, and the build process goes to the next step in the next build)
the error message is still unclear, but at least it doesn't fall into unexpected state.
> Update info.json only when ast_builder.rs gets parsed (fixes #156)

- rust/emitter/src/ast_emitter.rs
- rust/generated_parser/src/ast_builder.rs
- rust/parser/src/tests.rs
Added the following to AstBuilder, and removed workaround in AstEmitter.
https://tc39.es/ecma262/#sec-identifiers-static-semantics-assignmenttargettype
```
12.1.3 Static Semantics: AssignmentTargetType
IdentifierReference : Identifier
1. If this IdentifierReference is contained in strict mode code and
StringValue of Identifier is "eval" or "arguments", return invalid.
2. Return simple.
```
and also added some comments for spec steps.
currently `is_strict()` just returns `NotImplemented`.
So, script that contains any assignment to `eval` or `arguments` will fallback to C++
> Implement Early Erros for AssignmentTargetType, for arguments/eval (fixes #183)

- rust/emitter/src/ast_emitter.rs
- rust/interpreter/src/evaluate.rs
This adds support for array literals without holes or spread elements. For object literals this only supports "normal" data properties.
> Support simple array and object literals

- rust/emitter/src/ast_emitter.rs
opcode after conditional/unconditional jump should be JumpTarget.
> Emit JumpTarget after conditional jump in short circuit (fixes #199)

- rust/generated_parser/src/ast_builder.rs
Fixes #173 by not compiling scripts that use the string `"use strict"` *anywhere*.
> Hack: Prevent emission for scripts with 'use strict' directive.

- js_parser/load_es_grammar.py
- rust/generated_parser/src/ast_builder.rs
- rust/generated_parser/src/early_errors.rs
- rust/parser/src/lexer.rs
Added `TerminalId::NameMaybeKeyword` for the case the escape sequence was contained in name.
`IdentifierEarlyErrorsContext` now receives `TerminalId`, and use it for error check, instead of string comparison, as much as possible.
String comparison happens only for the following 3 cases:
* all cases for `TerminalId::NameMaybeKeyword`
* checking "arguments" for `TerminalId::Name`
* checking "eval" for `TerminalId::Name`
Also, to make this work, I've fixed lexer to geenrate `TerminalId::Implements` etc,
so that `TerminalId::Name` doesn't contain any contextual keywords.
> Use TerminalId in IdentifierEarlyErrorsContext to avoid redundant string comparison on identifiers

- rust/emitter/src/ast_emitter.rs
`array.elements.len()` would be fine as a stopgap, but I went ahead and
implemented what the C++ frontend does.
> Initialize new arrays to the expected length. Fixes #209.

- rust/ast/generate_ast.py
Preparation for generating scope information.
In most case the visitor pass don't want to modify how fields are visited, but want to perform some tasks before/after visiting fields,
for example, push/pop context, accumulate information collected while visiting fields.
> Add enter/leave to visitor to perform some operation before/after visiting fields

- rust/emitter/src/ast_emitter.rs
- rust/interpreter/src/evaluate.rs
- rust/interpreter/src/globals.rs
- rust/interpreter/src/lib.rs
- rust/interpreter/src/tests.rs
Implement method calls where the base/object is an ordinary expression and not super. I didn't notice any new failure when running with jstests or jittest.
> Implement method call

- .github/workflows/ci-daily.yml
- .github/workflows/ci-issues.yml
- .github/workflows/ci-push.yml
- .metrics/README.md
- .metrics/create-ci-branch.sh
- .metrics/fuzzbug_count_badge.py
- .metrics/fuzzbug_date_badge.py
- .metrics/generated_README.md
- .metrics/not_implemented_badge.py
- .metrics/not_implemented_count.py
- .metrics/populate_fuzzbug.sh
- .metrics/populate_not_implemented.sh
- README.md
What this does:
Creates a series of badges and counters in a separate repository `ci_results`. 
They look like this: 
This patch introduces 3 new ci tasks. On Push to master, on issue creation, and a crone job that runs once a day. At the moment we are tracking two tasks from #206 -- the only one that isn't working, or that i can't get to work in my test environment, is issues. It might work from master though.. not sure. If it is still failing after merge, I will try something else, maybe just rely on daily jobs or half day jobs.
This is pretty large, I can split it into subtasks. I will handle the byte writing separately as a daily task
> Update ci to handle fuzzbugs and notImplemented status

- README.md
cargo-fmt cannot be installed via `cargo install cargo-fmt` and is bundled with rustfmt
> fix #94 - do not use cargo-fmt

- rust/emitter/src/emitter.rs
there's corresponding change for rust-frontend
> Add all plain fields for stencil to EmitResult (fixes #253)

- Makefile
- README.md
I noticed while we were discussing cargo-fmt that we still had the git hooks outside of the make init file. This updates it so that githooks are set in the init file.
> move githooks initialization to make init

- rust/Cargo.lock
- rust/ast/Cargo.toml
- rust/driver/Cargo.toml
- rust/driver/src/demo.rs
- rust/emitter/Cargo.toml
- rust/emitter/src/lib.rs
- rust/generated_parser/Cargo.toml
- rust/generated_parser/src/ast_builder.rs
- rust/generated_parser/src/lib.rs
- rust/interpreter/Cargo.toml
- rust/interpreter/src/lib.rs
- rust/parser/Cargo.toml
- rust/parser/src/lib.rs
context in https://github.com/mozilla-spidermonkey/jsparagus/issues/310
so far:
* added `jsparagus-` prefix to all crates
* added alias to them by `extern crate jsparagus_NAME as NAME;` so that existing code doesn't have to be modified
now preparing corresponding change to rust-frontend
> Add jsparagus- prefix to all crates (fixes #310)

- .github/workflows/ci-generated.yml
- Makefile
This action introduces a way for us to automatically generate a `ci_generated` branch on push to master. The files generated are these ones: https://github.com/mozilla-spidermonkey/jsparagus/commit/7a277811102a52004d4276df8a52c87019bffd89
> create generated branch (fixes #316)

- Makefile
- rust/ast/generate_ast.py
- rust/ast/src/associated_data.rs
- rust/ast/src/lib.rs
- rust/ast/src/source_location.rs
This add the following:
* `NodeTypeId` that represents AST node type (basically a map from AST node type to integer)
* `NodeTypeIdAccessor` that adds `get_type_id` method for each AST node type, that returns `NodeTypeId`
* `AssociatedData`, that is a map from AST node (`NodeTypeId`+`SourceLocation`) to arbitrary  data
Assuming `AssociatedData` is created (`AssociatedData,insert`) while visiting AST node, and also the consumer will get (`AssociatedData.remove`) the data in the same order, the implementation is optimized for sequential access (`AssociatedData.next_index`).
`AssociatedData.allocate` and `AssociatedData.populate` are for the case when the order differs.
This is especially for the case that creating scope information.
The scope information is created at the end of the node …
> Add ast::AssociatedData (fixes #244)

- .github/workflows/ci-generated.yml
2 changes:
* Now generated files are stored in `refs/ci_generated/master` branch (previously `refs/heads/ci_generated`)
* previous change is reverted and merged, so that all revisions are inside history 
https://github.com/mozilla-spidermonkey/jsparagus/issues/333#issuecomment-592342818
`refs/ci_generated/master` isn't shown on GitHub UI, but you can see it via GitHub API.
https://api.github.com/repos/mozilla-spidermonkey/jsparagus/git/refs/ci_generated/master (doesn't yet exist)
Just to fetch it:
```
git fetch {remote_name} +refs/ci_generated/master
```
where `{remote_name}` is `origin` or `upstream` or something.
To checkout, you need to map it to an usual branch, and then checkout:
```
git fetch {remote_name} +refs/ci_generated/master:refs/remotes/{remote_name}/ci_generated/master
git …
```
> Use hidden branch for ci_generated, and merge previous head (fixes #333)

- crates/emitter/src/ast_emitter.rs
- crates/emitter/src/emitter.rs
- crates/emitter/src/lib.rs
- crates/emitter/src/reference_op_emitter.rs
replaces https://github.com/mozilla-spidermonkey/jsparagus/pull/234
now I think using public struct field (instead of function parameter) is less error-prone
(see https://gist.github.com/arai-a/fdcb6ddf1a94c62b3df028dc449212fc for more complex case)
> Add Get*Emitter, CallEmitter, NewEmitter, AssignmentEmitter (fixes #232)

- crates/emitter/src/emitter.rs
call ops pops callee, this, and arguments, but `emit_argc_op` was handling only argc
> Reflect callee/this use to stack depth (fixes #345)

- .githooks/pre-commit
Apparently under Ubuntu /bin/sh points to "dash", which does not support
substitution: https://stackoverflow.com/questions/20615217/bash-bad-substitution
> Use bash instead of sh for git fmt hook

- crates/emitter/src/ast_emitter.rs
- crates/emitter/src/emitter.rs
- crates/emitter/src/forward_jump_emitter.rs
There are 2 cases for jump target.
If the previous opcode falls-through, means, the jump target is a merge point, those 2 branches should have same stack depth.
If the previous opcode doesn't fall-through, the previous stack depth is unrelated, but it should overwrite the depth to the jump origin.
> Update stack depth at non-merge jump target

- crates/emitter/src/ast_emitter.rs
- crates/emitter/src/reference_op_emitter.rs
This just makes it so we use the code for ComputedMemberExpression that
was already added in #257.
No new failures with jit-tests or jstests.
> Enable support for CallElem

- README.md
This pull request adds documentation to the `Readme.md` file with 2 sections, one for running regression testing benchmarks, with the code added by @zbraniecki , and one for adding overall performance testing based on `real-js-samples` extracted by @Yoric.
(fix #144)
> Add Readme documentation on how to benchmark jsparagus.

- .github/workflows/ci-generated.yml
Given that cargo cannot fetch hidden branches, we should use normal branch for generated files branch.
> Use normal branch for generated files branch to make it visible to cargo

- crates/emitter/scripts/update_opcodes.py
- crates/emitter/src/ast_emitter.rs
- crates/emitter/src/emitter.rs
- crates/emitter/src/forward_jump_emitter.rs
- crates/emitter/src/opcode.rs
Depends on https://bugzilla.mozilla.org/show_bug.cgi?id=1620603
Most of emitter struct's methods directly map to opcode definition.
Changed it to be automatically generated from Opcodes.h definition (both macro and comment).
`Opcodes.h` is parsed by m-c/js/src/vm/jsopcode.py
maybe we can change `update_opcode` to also use it, but I'll leave it to other issue.
> Generate emitter methods from opcodes definition

- README.md
The README contains instruction for benchmarking jsparagus using Spidermonkey, however, it is missing a step needed to use the changes from the user while building SpiderMonkey.
> README: Add missing 'mach vendor rust' step.

- crates/emitter/scripts/update_opcodes.py
- crates/emitter/src/copy/BytecodeUtil.h
- crates/emitter/src/copy/Opcodes.h
- crates/emitter/src/lib.rs
- crates/emitter/src/opcode_info.rs
So far, added a function that returns the input files of opcode.rs (by storing them in the crate)
currently the following files are stored:
* `BytecodeUtil.h`
* `Opcodes.h`
SmooshMonkey can use it like the following, so that if there's any change in the input files,
the build fails.
the issue here is that there's false positive of the assertion failure,
where the change doesn't affect the opcode.rs.
we can extract necessary part, but I'm wondering where to put that code.
(currently, it's in Python script in jsparagus (`update_opcodes.py`), and not sure invoking it from m-c is reasonable...
maybe we can instead put the script in m-c, and use it from jsparagus to update opcode.rs
```
diff --git a/js/src/frontend/smoosh/Cargo.toml b/js/src/frontend/smoosh/Cargo.toml
index …
```
> Provide the input of opcode.rs to consumer (fixes #348)

- crates/parser/src/parser.rs
- crates/parser/src/simulator.rs
- jsparagus/emit/python.py
- jsparagus/emit/rust.py
- jsparagus/lexer.py
- jsparagus/parse_pgen_generated.py
- jsparagus/runtime.py
- tests/test_js.py
This issue fix #366.
It convert `CheckNotOnNewLine` to a boolean expression tested in the action which is calling it. If it returns false, then we do not take the epsilon edge and backtrack by popping the stack and adding shifted tokens to the replay stack.
This PR adds a JS test case for the python parser, extracted from SpiderMonkey test262 test suite.
I have not yet tested against test262 test cases, as my SM tree is out-of-sync.
> CheckNotOnNewLine backtracks to fallback on ASI if possible.

- js_parser/README.md
- js_parser/extract_es_grammar.py
Extract Early Errors sections (not in Annex)
```
./jsparagus_build_venv/bin/python \
js_parser/extract_es_grammar.py \
--target ee \
path/to/spec.html
```
Extract Early Errors sections in Annex
```
./jsparagus_build_venv/bin/python \
js_parser/extract_es_grammar.py \
--target ee-annex \
path/to/spec.html
```
Partial output for `--target ee-annex`:
```
IdentifierStart :: `\` UnicodeEscapeSequence
* It is a Syntax Error if the SV of |UnicodeEscapeSequence| is none of *"$"*, or *"_"*, or the UTF16Encoding of a code point matched by the |UnicodeIDStart| lexical grammar production.
IdentifierPart :: `\` UnicodeEscapeSequence
* It is a Syntax Error if the SV of |UnicodeEscapeSequence| is none of *"$"*, or *"_"*, or the UTF16Encoding of either <ZWNJ> or <ZWJ>, or the UTF16Encoding of a Unicode …
```
> Support scraping Early Errors and Early Errors in Annex in extract_es_grammar.py (fixes #217)

- crates/emitter/src/ast_emitter.rs
We don't yet support direct eval, so return NotImplemented for it.
> Return NotImplemented for direct eval

- crates/generated_parser/src/ast_builder.rs
- js_parser/es-simplified.esgrammar
For now, just return `NotImplemented` from `AstBuilder`, without generating AST nodes
> Return NotImplemented for static class field (fixes #381)

- crates/parser/benches/parser.rs
- crates/parser/src/tests.rs
This fixes the `cargo test` and `cargo bench` in the parser crate.
> Fix parser tests and bench

- crates/ast/src/source_atom_set.rs
- crates/emitter/src/ast_emitter.rs
- crates/emitter/src/compilation_info.rs
- crates/emitter/src/emitter.rs
- crates/emitter/src/emitter_scope.rs
- crates/emitter/src/frame_slot.rs
- crates/emitter/src/gcthings.rs
- crates/emitter/src/lib.rs
- crates/emitter/src/reference_op_emitter.rs
- crates/emitter/src/scope.rs
- crates/emitter/src/scope_notes.rs
- crates/emitter/src/scope_pass.rs
- crates/emitter/src/script_atom_set.rs
- crates/interpreter/src/evaluate.rs
Implements scope handling for global and block lexical, excluding `eval` (that needs environment object):
* Scope pass:
* Added `BindingName` that's same thing as C++ one
* Added `GlobalScopeData` and `LexicalScopeData`, corresponds to C++ `*Scope::Data`
* Added `ScopeDataMap`, to associate scope data to AST node
* Add `ScopePass` that replaces previous scope pass:
* visits AST nodes and calculate scope/bindings, that's mostly scope handling part of C++ Parser, but uses similar structure as the spec
* Emitter pass:
* When entering/leaving script and block, handle scope, and emit necessary ops
* Support `VariableDeclarationStatement`, to test scopes
* Support `GCThing` with scope variant
* Added prologue/main distinction, for `DefVar` etc
* Support `ScopeNote`, that's same as C++ one
* …
> Implement scope handling for global and block (fixes #215, fixes #221, fixes #245)

- .github/workflows/rust.yml
- Makefile
This should catch non-default crates issue, and also catch warnings.
> Treat warning as error in automation (fixes #258) and build all crates

- crates/ast/src/source_atom_set.rs
- crates/emitter/src/ast_emitter.rs
- crates/emitter/src/emitter.rs
- crates/emitter/src/lib.rs
- crates/generated_parser/src/ast_builder.rs
- crates/generated_parser/src/early_errors.rs
- crates/generated_parser/src/error.rs
- crates/interpreter/src/evaluate.rs
- crates/parser/src/lexer.rs
- crates/parser/src/lib.rs
- crates/parser/src/parser.rs
- crates/parser/src/simulator.rs
- crates/parser/src/tests.rs
- jsparagus/emit/rust.py
3 changesets:
* 1st one adds `'alloc` to `ParserError` and parser `Result`.  with temporary `PhantomData` to consume the lifetime parameter
* 2nd one changes the `SourceAtomSet` to store `&'alloc str` instead of `String`, and change `String` to `&'alloc str` in other structs, and also remove `PhantomData` added in previous one
* 3ed one changes `SourceAtomSet` to use `IndexSet` instead of `HashMap`
the corresponding change will be in https://bugzilla.mozilla.org/show_bug.cgi?id=1623172
>  Do not allocate String while atomization (fixes #397) 

- crates/interpreter/src/evaluate.rs
- crates/interpreter/src/tests.rs
I also added a test for if statements with statement blocks :tada:
I think it might be useful to run interpreter tests as well, this would basically allow us to test a very small subset and bytecode generation. So far updating the interpreter has been quite painless, and we can just not test stuff that is too complicated.
> Fix interpreter tests

- Makefile
- crates/emitter/src/lib.rs
`make check` wasn't running `cargo test` for inner crates.
fixed it, and also fixed emitter test
> Fix make check

- Cargo.lock
- crates/driver/Cargo.toml
- crates/driver/src/demo.rs
- crates/driver/src/main.rs
- crates/interpreter/src/evaluate.rs
- crates/interpreter/src/globals.rs
- crates/interpreter/src/tests.js
- crates/interpreter/src/tests.rs
- crates/interpreter/src/value.rs
I changed the driver to not output any of the verbose debug info like AST etc. by default. If that is to controversial we could probably change the default value. Personally I find the EmitResult especially too verbose.
The rest are just incremental improvements to the interpreter. Adding `assertEq` especially makes it possible to write tests in JS. Together with `include_str` we can add all new tests to `tests.js` going forward.
> Interpreter improvements

- crates/driver/src/demo.rs
- crates/driver/src/main.rs
- crates/interpreter/src/globals.rs
- crates/interpreter/src/value.rs
- crates/parser/src/lexer.rs
- crates/parser/src/lib.rs
- crates/parser/src/numeric_value.rs
- crates/parser/src/tests.rs
Supports `NonDecimalIntegerLiteral` and underscores between `DecimalDigits`.
for non-integer case, this still uses Rust standard `parse` function.
I suppose this yields the same result, but have to confirm.
(at least this doesn't hit any problematic case while working on BinAST, and I'd like to avoid porting dtoa.c to rust :P )
`BigInt` is not yet supported, given we don't yet have the storage for the result.
> Support non-decimal literals (fixes #263)

- crates/emitter/src/free_name_tracker.rs
- crates/emitter/src/lib.rs
- crates/emitter/src/scope.rs
- crates/emitter/src/scope_pass.rs
3 changesets with 2 cleanups and 1 main change (the last one).
The main one introduces `FreeNameTracker` that tracks the following:
* names used in the current scope: `used_names`
* names used and not yet defined in inner scopes
* if it's in the same script, it's in `used_names`
* if it's in the different script, it's in `closed_over_names`
* names defined in the current scope: `def_names`
when creating `BindingName`, the above info is used to compute `is_closed_over`,
and also when leaving the scope, unresolved (not-yet-defined) use are propagated to outer scope
This patch actually doesn't change anything, given currently we have only one script, that is global,
and haven't supported function.
Once function scope is introduced, `ContextStack::pop` is supposed to call …
> Track free names for each scope (fixes #416)

- .gitignore
- Makefile
- js_parser/extract_es_grammar.py
- js_parser/load_es_grammar.py
- js_parser/parse_esgrammar.py
- jsparagus/actions.py
- jsparagus/emit/python.py
- jsparagus/extension.py
- jsparagus/gen.py
- jsparagus/grammar.py
- jsparagus/lexer.py
- jsparagus/ordered.py
- jsparagus/parse_pgen_generated.py
- jsparagus/runtime.py
- jsparagus/types.py
- jsparagus/utils.py
- requirements.txt
- tests/test.py
- update.sh
Things to know about mypy:
- Annotations are optional, and it's ok (and normal) to have a codebase partially annotated.
- `python` does not use these annotations to type-check values at run time.
- They are only checked when you run the mypy tool.
- If you write `if instanceof(foo, str):` then mypy knows `foo` is a `str` in the `if` body.
- If you write `assert instanceof(foo, str)`, then mypy **assumes** that the assertion is correct and that `foo` is a `str` afterwards. Your assertion might be wrong!! So avoid this where possible. It's actually making mypy do less type checking.
> Add type annotations to some Python methods (and miscellaneous minor fixes)

- crates/ast/generate_ast.py
- crates/driver/src/demo.rs
- crates/emitter/src/lib.rs
- crates/interpreter/src/tests.rs
- crates/scope/src/lib.rs
- crates/scope/src/pass.rs
To collect references to inner functions, visitor should use immutable reference
with explicit lifetime parameter.
> Make visior immutable, and use reference with lifetime (fixes #447)

- crates/emitter/src/ast_emitter.rs
- crates/emitter/src/block_emitter.rs
- crates/emitter/src/emitter_scope.rs
- crates/emitter/src/lib.rs
- crates/emitter/src/script_emitter.rs
- crates/interpreter/src/evaluate.rs
Moved script and block related code into helper, with a fix for #434 that adds newly added CheckGlobalOrEvalDecl opcode before script
> Add ScriptEmitter and BlockEmitter (fixes #434)

- crates/emitter/src/emitter.rs
- crates/emitter/src/scope_notes.rs
https://searchfox.org/mozilla-central/rev/064b0f9501ad76802853b43f18e33d8713fd54d3/js/src/vm/SharedStencil.h#76-78
it should be gcthings index, not scope index
> Fix ScopeNote to store GCThingIndex instead of ScopeIndex

- crates/parser/src/lexer.rs
- crates/parser/src/numeric_value.rs
- crates/parser/src/tests.rs
The following were not able to handle the case that number overflows from 53bit (integer part of f64)
* `parse_decimal_int`
* `parse_binary`
* `parse_octal`
* `parse_hex`
That the resulting number has error around 54+bits.
For `parse_decimal_int`, it can fallback to `parse_float`, that's basically a slow path for the case when the literal contains `_`.
For other cases, I cannot find a simple way to parse too big non-decimal in Rust,
so for now it returns NotImplemented.
> Fix too big decimal integer literals, and return NotImplemented for too big non-decimal integer literals (fixes #445)

- crates/parser/src/lib.rs
- crates/parser/src/parser.rs
- crates/parser/src/queue_stack.rs
- crates/parser/src/simulator.rs
- jsparagus/emit/rust.py
This work is described here: https://github.com/mozilla-spidermonkey/jsparagus/issues/378#issuecomment-602742753
Doing more runs with the `real-js-samples` highlighted that this change improved the performance from: `~84 ns/byte` to `~73 ns/byte`. (13% improvement)
> Add parser stack and lookahead in the same container.

- Makefile
- jsparagus/aps.py
- jsparagus/gen.py
This is commit is extracted from #429 and is used in #430 work.
This extract the APS and Edge classes from the ParseTable and move it to its own file.
> Factor APS out of gen.py

- crates/driver/src/demo.rs
- crates/emitter/src/ast_emitter.rs
- crates/emitter/src/emitter.rs
- crates/emitter/src/lib.rs
- crates/emitter/src/stencil.rs
- crates/interpreter/src/evaluate.rs
- crates/interpreter/src/tests.rs
* moved `EmitResult` fields specific to a script into `ScriptStencil`
* added `EmitResult.scripts` that's an array of `ScriptStencil`, the first one is global, and others are inner functions
> Separate ScriptStencil from EmitResult (fixes #452)

- .gitignore
This file is produced while debugging the generated parser, as it is useful to browse the generated content. It is used for either parsing ESGrammar files, or the tests cases.
Let's ignore it.
> Ignore python parser generated at the top-level for debugging.

- jsparagus/actions.py
- jsparagus/aps.py
- jsparagus/gen.py
When doing grammar changes or parser passes, the state might be renumbered.
While this is a useful thing for optimization, this makes thing terribly hard
for debugging.
This change introduces a stable_hash, which relies on the stringification of
productions and actions.
NOTE, this is a work in progress because I have not tested the correctness of the hash (for example whether we get a different state number for the reduce action) and have not checked whether we have collision or not while shrinking the hash number.
> Parse Table: Add stable state numbering.

- jsparagus/aps.py
- jsparagus/gen.py
- tests/test.py
This issue fixes the #464 , by changing the way we handle reduce actions.
Instead of handling reduce actions by always reducing the non-terminal which is being reduced, we let the APS discover which state allow the non-terminal to be replayed, even after a Lookahead action.
This work is based on top of #465 and extracted from [the branch](https://github.com/nbp/jsparagus/tree/filter-states-and-replay-actions) which aim to solve #430 by adding Replay action.
However, to handle this case, we had to remove the guarantee that `reduce_path` should always reduce to a state capable of shifting the reduced non-terminals, as long as the grammar is inconsistent. Thus, a new flag is added to the parse table to quickly check whether we expect to be working with an inconsistent parse table or not, in …
> Fix ignored lookahead in inconsistent parse tables

- Makefile
Without this tiny patch, any mypy failure will prevent all other tests from running.
> `make check -k` dynamic test should run after mypy failure.

- crates/parser/benches/parser.rs
Fixes the `cargo bench` command on the parser.
> Fix parser benchmark

- jsparagus/actions.py
- jsparagus/emit/python.py
- jsparagus/emit/rust.py
- jsparagus/lr0.py
- Add Accept action, to reduce complexity around handling FunCall.
- Rust backend: split actions from conditionals, to later be able to include the
destination as part of the code handling conditionals.
- Create a RustActionWriter to aggregate all tasks dedicated to actions in a
single place.
This patch is extracted from the patch queue I have to work on #430. I want to make sure that the modification made as part of #430 are coming from it and not due to all the side modifications. So this is an attempt to minimize the amount of unique changes related to this patch queue.
This patch should not impact performance.
> Rust backend: Split the code for emitting Action code.

- crates/ast/src/arena.rs
- crates/generated_parser/src/ast_builder.rs
Using `alloc_with` will help the compiler by hinting it that there is no need to
copy the value to the stack as argument before storing it on the heap.
See the [documentation of bumpalo::alloc_with](https://docs.rs/bumpalo/3.0.0/bumpalo/struct.Bump.html#method.alloc_with) for more details.
This change is a `1-3 ns/byte` improvement on real-js-samples. (when inlined in the reduce functions)
> AST Builder: Use alloc_with instead of alloc to avoid extra copies.

- crates/emitter/src/ast_emitter.rs
- crates/emitter/src/control_structures.rs
`emit_variable_declaration_statement` doesn't push any value, given it's statement.
so `VariableDeclarationOrExpression::Expression` branch should also pop the value pushed by `emit_expression`.
for consistency, changed `update` part also to pop the value.
`test` closure should still leave the value, given the value is used for condition.
> Pop values pushed by init/update in c-style-for in the caller for consistency with declaration (fixes #493)

- crates/emitter/src/ast_emitter.rs
non-local jumps needs scope handling (https://github.com/mozilla-spidermonkey/jsparagus/issues/495)
so disabling break/continue support until that part gets ready.
now running try with this, to check remaining failure
https://treeherder.mozilla.org/#/jobs?repo=try&tier=1%2C2%2C3&revision=328faf2231440985821bdf8d456e5c74ab732606
> Disable break/continue until scope handling gets ready

- Cargo.lock
- crates/generated_parser/Cargo.toml
- crates/generated_parser/src/ast_builder.rs
- crates/generated_parser/src/early_errors.rs
- crates/generated_parser/src/error.rs
- crates/generated_parser/src/lib.rs
- crates/parser/src/lexer.rs
- crates/parser/src/parser.rs
- crates/parser/src/simulator.rs
- crates/parser/src/tests.rs
This work is divided in 2 patches, the first one add the `std::boxed::Box` type as well as `.into()` calls where necessary, and the second one adds assertions to avoid accidental regressions.
Note `std::boxed::Box` is explicitly used to avoid confusing it with `arena::Box`, and `.into()` is used instead of `Box::new(…)` to avoid name clashes with `arena::Box`.
This changes need some changes in smoosh monkey. I will link the bugzilla issue here later.
> Box the ParseError to reduce the size of Result type.

- crates/scope/src/builder.rs
- crates/scope/src/data.rs
To support the case that `ScopeIndex` isn't allocated contiguously, changed `AliasPrevious` to `Alias(ScopeIndex)`
this will be necessary when there is another scope inside parameter, and function body tries to refer parameter scope.
> Fix ScopeData::Alias to hold ScopeIndex (fixes #485)

- crates/generated_parser/src/ast_builder.rs
- crates/generated_parser/src/context_stack.rs
- crates/generated_parser/src/early_errors.rs
This splits labels out of the bindings vec, and also updates the label checking helper methods to not use the AST. The last commit is not critical, and can be removed (we can continue to rely on the statements).
> Move labels into their own vec; fixes #503

- crates/parser/src/lexer.rs
- crates/parser/src/lib.rs
- crates/parser/src/parser.rs
- crates/parser/src/simulator.rs
- crates/parser/src/tests.rs
The lexer is currently returning an `AdvanceResult`, which is then converted to a `Token`, and copied by the `Parser` to the bump allocator space. This patch move the allocation made by the parser as soon as possible, into the Lexer, and the lexer only write this data once straight to memory, where it is expected to be found by the parser.
This modifications is aimed at the top-level loop which was representing 8% of SmooshMonkey profile.
https://perfht.ml/2xHcY0r , this change, in addition to #505 , divide by 3 the time spent in this function.
> Lexer returns allocated token

- crates/emitter/src/control_structures.rs
- crates/emitter/src/dis.rs
- crates/generated_parser/src/early_error_checker.rs
While working on #515 i noted that there were a few problems with my label implementation. Labels were not breaking correctly. This fixes that, and also cleans up some formatting in error stacks, and adds more debug information.
> Fix labels and add more information to disassembly

- crates/emitter/src/ast_emitter.rs
- crates/emitter/src/control_structures.rs
- crates/emitter/src/emitter.rs
- crates/emitter/src/emitter_scope.rs
- crates/emitter/src/gcthings.rs
- crates/emitter/src/scope_notes.rs
fixes #495, depends on #516
The first commit tries to make working with internal control structure jumps safer: I already made the mistake once of emitting a bytecode between recording the offset and emitting the jump, which lead to hard to trace errors.
The second commit adds scopenotes to loops and labels
The final two commits are where #495 is really resolved. I used a similar approach to forward jumps. A `NonLocalJumpControl`, when it prepares to jump, returns a collection of scope holes that need to be closed. After a jump, those must be called. The rest of the changes are helpers to make this possible.
> Scope notes for breaks and continues

- jsparagus/actions.py
- jsparagus/lr0.py
This is a simple clean-up, which removes unused code.
> Remove unused alias set fields from actions.

- crates/parser/src/parser.rs
- crates/parser/src/simulator.rs
- jsparagus/emit/rust.py
This change replace the Term enum which was wrapping the enumerated type of
TerminalId and NonterminalId values. Despite the non-overlapping ranges of
numbers, Rust kept a single bit to distinguish between a Terminal and a
Nonterminal.
This change encode a Term as a single integer, as it was expected to be compiled
to. Note, this is using u32 instead of the minimal u16 representation as u32 is
faster to load and write to memory.
This change optimize the execution by reducing the Smoosh/Spider ratio from ~1.47 to ~1.44, when added on top of other optimizations.
> Replace Term enum by a simple number.

- crates/stencil/src/function.rs
method can be generator, and the assertion shouldn't be there
> Remove wrong assertion about generator

- jsparagus/actions.py
- jsparagus/aps.py
- jsparagus/emit/python.py
- jsparagus/parse_table.py
This change is needed as part of the work on #430, as `FilterState` action is introduced, an `Action` can hold a state index. When making changes to the parse table, we should keep these state indexes up-to-date.
> Rewrite states within Actions.

- jsparagus/ordered.py
This is a simple addition which would later be used to check that we do not have multiple conditions with identical conditions. If so, which should not happen, the state would be inconsistent.
This would be used when adding FilterState actions.
> Add isdisjoint to OrderedSet and OrderedDrozenSet.

- jsparagus/actions.py
- jsparagus/aps.py
- jsparagus/emit/python.py
- jsparagus/emit/rust.py
- jsparagus/lr0.py
- jsparagus/parse_table.py
The 2 actions used to be joined but will no longer remain joined. Thus, `update_stack` is used to express how the parser stack should be mutated, and `follow_edge` expresses whether the epsilon edge on which the action is attached should be followed or not. Reduce actions are not following the epsilon edges, as they follow the parser stack head, whereas Unwind action would follow the epsilon edge and manage the parser stack with actions, resulting in a split of concepts between the ordinary stack automaton and a regular automaton managing the parser stack.
- Add Unwind action. (not yet used to generate code)
- Change Reduce action to wrap the Unwind action with no follow_edge.
- Add StackDiff to express parser stack mutations.
- Add Action.update_stack_with to return a StackDiff.
This …
> Distinguish Action.update_stack from Action.follow_edge.

- jsparagus/emit/rust.py
- jsparagus/parse_table.py
- jsparagus/utils.py
This PR changes the way actions are generated to prevent hitting an LLVM corner case when compiling action function and also improve the optimizations applied to each action, by not giving up.
This would become much more important as `FilterStates`, `Unwind` and `Replay` actions are added and they increase the number of states which are jumping to each others.
> Split action function

- crates/generated_parser/src/lib.rs
- crates/generated_parser/src/traits/mod.rs
- jsparagus/emit/rust.py
Simple patch which move the parser_trait function out of the rust backend.
> Move the ParserTrait out of the generated code.

- crates/emitter/src/ast_emitter.rs
- crates/interpreter/src/evaluate.rs
Finally was able to test this in SM - running `debugger` without this patch throws that `TODO` error, and it's just a no-op with this patch.
Closes #225
> Implement `debugger` statement

- Cargo.toml
- mozconfigs/smoosh-debug
- mozconfigs/smoosh-opt
- src/bin/smoosh_tools.rs
This is Rust version of [smoosh-tools](https://github.com/arai-a/smoosh-tools/).
With this, we can build SpiderMonkey JS shell with SmooshMonkey enabled, and with local jsparagus with the following command, in jsparagus directory:
```
cargo run --bin smoosh_tools build
```
or, the following until another binary is added:
```
cargo run build
```
Prerequisite:
* mozilla-central is placed next to jsparagus (otherwise, specify path by `cargo run --bin smoosh_tools build PATH_TO_MOZILLA_CENTRAL`)
* `./mach bootstrap` is done
This has the following commands (from usage):
```
Usage:
cargo run --bin smoosh_tools build [--opt] [PATH_TO_MOZILLA_CENTRAL]
Build SpiderMonkey JS shell with SmooshMonkey enabled,
using this jsparagus clone, instead of vendored one
PATH_TO_MOZILLA_CENTRAL can be omitted …
```
> Add smoosh_tools

- crates/generated_parser/src/traits/mod.rs
- crates/parser/src/parser.rs
- crates/parser/src/simulator.rs
- jsparagus/actions.py
- jsparagus/aps.py
- jsparagus/emit/python.py
- jsparagus/emit/rust.py
- jsparagus/parse_table.py
- jsparagus/runtime.py
This work is part of #430 and add the `FilterStates` action as well as the code it produces in both the Python and Rust backend.
At the moment no phase of the parse table is making use of this code, but this would be part of the upcoming PR.
@jorendorff I think you might want to give a look at these changes as it is a corner stone from moving away from the default style of parse tables.
> Add FilterState action.

- .github/workflows/smoosh-status.yml
- Makefile
- README.md
- smoosh_status.py
This adds an automation that does:
* checks the latest SmooshMonkey build (SM(nu) job) result and test (debug SM(smoosh) job) result
* write the result into files in ci_smoosh_status branch (see https://github.com/arai-a/jsparagus/tree/ci_smoosh_status for example)
currently the automation runs every hour (maybe we can reduce the frequency tho)
and also this patch adds badges that uses the result (see https://github.com/arai-a/jsparagus)
the result is written into multiple files.
this is to make it easier to use it from smoosh_tools eventually
(so that it can checkout known good revisions)
> Add SmooshMonkey build/test status badge (fixes #569)

- README.md
Forgot to fix the badge source URL from my fork to official one.
this is going to be merged after the first automation runs (otherwise the link will be dead)
> Fix badge source to canonical repo

- crates/generated_parser/src/traits/mod.rs
- crates/parser/src/parser.rs
- crates/parser/src/queue_stack.rs
- crates/parser/src/simulator.rs
- jsparagus/actions.py
- jsparagus/aps.py
- jsparagus/emit/python.py
- jsparagus/emit/rust.py
- jsparagus/runtime.py
Previously `APS.shift_next` was maintaining the invariant that the state was always the state of the last edge in the shift list, which is emulating the Parser stack.
Now, as we want to remove unnecessary iteration of the `shift` function of the parser, we want to be able to express transitions which are in the parse table by using `Actions` when possible. As a consequence, the state of the parser might momentarily no longer correspond to the last shifted state of the Parser.
This case can happen, when executing an `Unwind` action which is not wrapped with a `Reduce` action, when executing a `Replay` action, when evaluating an action where the state does not already match such as `FilterState`.
However, an assertion is raised if a terminal or non-terminal is shifted while the state does …
> Add replay action

- benchmarks/compare-spidermonkey-parsers.js
- src/bin/smoosh_tools.rs
The bench command will look for a a checkout of [real-js-samples](https://github.com/Yoric/real-js-samples) and use it for
comparing both SpiderMonkey and SmooshMonkey parsers.
It relies on the `benchmarks/compare-spidermonkey-parsers.js` file as a harness to
run both parsers on a all files contained in a directory.
The directory is by default set to the real-js-samples, or it can be overriden
by using the `--samples-dir=<DIR>` command line option.
>  Add smoosh_tools bench command.

- Cargo.lock
- crates/parser/Cargo.toml
- crates/parser/src/lib.rs
- crates/parser/src/simulator.rs
This fixes #586 by baking it the currently assumed lookahead necessary to be replayed in the simulator.
This improves the relative SpiderMonkey parser speed from ~3.43 to ~3.00.
> Avoid allocation by baking-in current lookahead range in the simulator.

- crates/ast/ast.json
- crates/generated_parser/src/ast_builder.rs
- js_parser/es-simplified.esgrammar
supports the following
* `obj.#foo = x` (change in `private_field_expr`)
* `obj?.#foo` (JSON, and `optional_private_field_member_expr_tail`)
* `obj?.foo.#bar` (JSON and `optional_private_field_member_expr`)
> Support private fields in optional chain and assignment target

- crates/scope/src/builder.rs
- crates/stencil/src/scope.rs
https://searchfox.org/mozilla-central/rev/31d8600b73dc85b4cdbabf45ac3f1a9c11700d8e/js/src/frontend/Stencil.h#254
https://searchfox.org/mozilla-central/rev/31d8600b73dc85b4cdbabf45ac3f1a9c11700d8e/js/src/frontend/EmitterScope.cpp#697
https://searchfox.org/mozilla-central/rev/31d8600b73dc85b4cdbabf45ac3f1a9c11700d8e/js/src/frontend/SharedContext.h#475
creating `ScopeCreationData` for function's extra body var needs `funHasExtensibleScope()` information,
> Add function_has_extensible_scope to extra body var scope

- jsparagus/actions.py
- jsparagus/aps.py
- jsparagus/parse_pgen_generated.py
- jsparagus/parse_table.py
This is the final patch which introduces usage of `FilterState` and `Replay`, fixing #430 . This change mainly adds the phase which replaces the `Reduce` operations by `Unwind`, `FilterState` and `Replay` actions.
Still this is not the final set of changes as more optimization are coming after, but are simply ParseTable optimization, made by folding state together or abstract the replay queue as state arguments, allowing to generate code which executes faster.
> Optimize with filter and replay

- crates/scope/src/builder.rs
- crates/stencil/src/scope.rs
- crates/stencil/src/script.rs
* Lazy Function needs enclosing scope information, so stored it into `ScriptStencil`
* Also made `FunctionScopeData` fields public
* Also stored Function's `ScriptStencilIndex` (`FunctionIndex` in m-c side) in `FunctionScopeData`
> Add more function-related fields 

- crates/scope/src/builder.rs
- crates/stencil/src/script.rs
I mixed up toStringStart and sourceStart.
https://searchfox.org/mozilla-central/rev/b2395478c6adf6e5b241be1610fb1d920ed995ed/js/src/vm/JSScript.h#1499-1504
when we hit parameter start, we should set sourceStart, instead of toStringStart.
> Fix source extent for function

- crates/emitter/src/function_declaration_emitter.rs
- crates/scope/src/builder.rs
- crates/stencil/src/scope.rs
- crates/stencil/src/script.rs
* `FunctionScopeData.is_arrow`  
https://searchfox.org/mozilla-central/rev/b2395478c6adf6e5b241be1610fb1d920ed995ed/js/src/frontend/Stencil.h#219
* `ScriptStencil.{is_standalone_function, was_function_emitted, is_singleton_function}`  
https://searchfox.org/mozilla-central/rev/b2395478c6adf6e5b241be1610fb1d920ed995ed/js/src/frontend/Stencil.h#504-514
> Add more fields

- .github/workflows/real-js-benchmark.yml
- src/bin/smoosh_tools.rs
This change adds a Github workflow which is used to build and benchmark
jsparagus using smoosh_tools.
At the moment there is no eye candy reporting of the data which is being generated and the interested person has to visit the corresponding CI build to find the data. Nor does the build "fails" if a regression occur.
Note, the host used for running this Github Action benchmark is currently turned on on-demand. Ping me over [matrix](https://chat.mozilla.org/#/room/#js-frontend:mozilla.org) to turn it on when needed.
> Add real-js-samples benchmark CI.

- crates/ast/src/source_atom_set.rs
This is simple attempt at addressing the `SourceAtomSet::insert` cost of the lexer ( #589 ).
> Pre-allocate SourceAtomSet to cover 75% of the loaded scripts.

- jsparagus/parse_pgen_generated.py
- jsparagus/parse_table.py
This code prevent us from generating useless FilterStates conditions when there would be only one FilterStates edge generated.
FilterStates list the states which are expected to be at the top of the parser stack, and this list is exhaustifs, and no other state should be present. If there is exactly one FilterStates, then it must contain all the possible top-state of the parser stack, and all would execute the same thing afterward. This code simply do not produce the FilterStates edge in such case.
> Avoid filter states

- jsparagus/actions.py
- jsparagus/parse_table.py
When Replay precedes an Unwind action, we can remove as many replayed terms from
the Unwind action, thus avoiding stack manipulation while replaying and stack
manipulation while unwinding.
> Fold Replay and Unwind action.

- crates/scope/src/builder.rs
- crates/scope/src/pass.rs
We weren't visiting `this` expression.
the existence of `this` affects function's script's flag.
also, the condition to declare arguments were flipped.
> Visit this, and fix condition to declare arguments

- jsparagus/actions.py
- jsparagus/aps.py
- jsparagus/emit/python.py
- jsparagus/emit/rust.py
- jsparagus/parse_pgen_generated.py
- jsparagus/parse_table.py
This set of changes add the ability to add argument to action states. These arguments are used to account for the number of elements in the replay list.
These changes also make use of these arguments to fold even more the `Replay` action in the following `Unwind` action, to the point where we are capable of even removing the `Replay` action, however, this implies that `Unwind` action can now have a negative number of replay arguments.
This change should optimize the execution by removing the need for adding elements to the replay-list including their associated state, and thus taking a short-cut in the states taken by the LR parser.
> Add state arguments for replay

- jsparagus/emit/python.py
- jsparagus/parse_pgen_generated.py
Using FunCall causes the same method names to be declared multiple time based on
the offset of the arguments of the function. This removes this duplication by simply aggregating method names and the number of arguments instead.
> Remove duplicates in python default methods.

- .metrics/populate_not_implemented.sh
- crates/emitter/src/lib.rs
- crates/scope/src/builder.rs
- crates/scope/src/lib.rs
- crates/scope/src/pass.rs
We don't yet support several syntax that affects scope.
Without lazy functions, most of those syntax are rejected by emitter.
Lazy function's body isn't handled by emitter, and we need to reject them in scope analysis.
> Reject unsupported scope (fixes #602)

- crates/scope/src/builder.rs
- src/bin/smoosh_tools.rs
1st and 3rd patches are just cleanup.
the main patch (2nd) moves the Annex B function handling (especially, adding the function name to defined variable in FreeNameTracker) before propagating free names to outer scope,
so that function body-level binding created by Annex B is reflected to free name tracking, and any use inside the function body won't close over enclosing scope's binding.
> Fix Annex B function handling for closed over binding

- crates/scope/src/builder.rs
- crates/scope/src/pass.rs
- crates/stencil/src/script.rs
syntax-only parsing doesn't need `ScopeData`.
So nested function's `ScriptStencil`s are created without `enclosing`.
`ScopeBuilder::SyntaxOnly*` variants collects minimal information necessary to build function stencils and closed over bindings.
non-function variants just uses `BaseScopeBuilder` that tracks free/defined names.
function variants uses newly-introduced `SharedFunctionParametersScopeBuilder`/`SharedFunctionBodyScopeBuilder`,
that's partial data of `FunctionParametersScopeBuilder`/`FunctionBodyScopeBuilder` (so, part of fields and methods are moved/copied there)
when entering/leaving block/function, if it's syntax-only mode, it pushes/pops `SyntaxOnly*` variants, without touching `ScopeData` (`ScopeDataMapBuilder.scopes`).
currently, syntax-only mode is enabled when entering …
> Support syntax-only mode in scope builder (fixes #603)

- crates/stencil/src/copy/Opcodes.h
- crates/stencil/src/opcode.rs
https://bugzilla.mozilla.org/show_bug.cgi?id=1722002 changed the behavior of JSOp::CheckReturn.
we don't use `check_return`, so just updated Opcode.h
will be vendored in https://bugzilla.mozilla.org/show_bug.cgi?id=1723457
> Update opcode for bug 1722002

- crates/emitter/src/emitter.rs
- crates/stencil/src/copy/BytecodeFormatFlags.h
- crates/stencil/src/copy/Opcodes.h
- crates/stencil/src/opcode.rs
- update_stencil.py
https://bugzilla.mozilla.org/show_bug.cgi?id=1726533 added `JOF_SHAPE` and modified `JSOp::NewObject`.
we don't use it so far, so just updated opcode definition.
> Update opcode for bug 1726533

- crates/stencil/src/copy/Opcodes.h
- crates/stencil/src/opcode.rs
https://bugzilla.mozilla.org/show_bug.cgi?id=1740737 changed the definition of `JSOp::OptimizeSpreadCall`
we don't use it, so just updated the definition
> Update opcode for bug 1740737

- crates/stencil/src/copy/Opcodes.h
- crates/stencil/src/opcode.rs
`JSOp::DynamicImport` is updated by https://bugzilla.mozilla.org/show_bug.cgi?id=1736060
we're not using it, so just updated the file.
> Update opcode for bug 1736060

- crates/stencil/src/copy/Opcodes.h
- crates/stencil/src/copy/StencilEnums.h
- update_stencil.py
https://bugzilla.mozilla.org/show_bug.cgi?id=1730843 modified `Opcodes.h`, with extra macro to conditionally enable those opcodes for Record and Tuple.
there are 2 places that reads `Opcodes.h`, `m-c/js/src/vm/jsopcode.py` and `jsparagus/update_stencil.py`.
`m-c/js/src/vm/jsopcode.py`'s pattern ignores the extra macro, and those opcodes are included in the return value.
`jsparagus/update_stencil.py`'s pattern filtered out the opcodes with extra macro.
So that results in inconsistency, and the first patch here fixes it by filtering out Record and Tuple opcodes from the value returned from `m-c/js/src/vm/jsopcode.py`.
(eventually we could drop the code that parses Opcodes.h from `jsparagus/update_stencil.py`, but that's for other bug)
> Update opcodes for bug 1730843

- crates/emitter/src/emitter.rs
- crates/stencil/src/copy/Opcodes.h
- crates/stencil/src/copy/StencilEnums.h
- crates/stencil/src/opcode.rs
- crates/stencil/src/script.rs
[bug 1282976](https://bugzilla.mozilla.org/show_bug.cgi?id=1282976) removed `JSOp::LambdaArrow`, and added `FunctionHasNewTargetBinding` flag for `new.target`.
we don't support them, so no change except the definition.
> Update opcode for bug 1282976

- crates/emitter/src/emitter.rs
- crates/stencil/src/copy/BytecodeFormatFlags.h
- crates/stencil/src/copy/Opcodes.h
- crates/stencil/src/opcode.rs
https://bugzilla.mozilla.org/show_bug.cgi?id=1766730 removed JSOp::Retsub and JSOp::ResumeIndex.
there's no consumer in jsparagus, so just updated the definition.
> Bump opcode for Bug 1766730

- src/bin/smoosh_tools.rs
After `Cargo.toml` in `mozilla-unified` to point local jsparagus, it requires `cargo update -p gkrust-shared` command to reflect the change.
https://searchfox.org/mozilla-central/rev/997a56b018662e2940c99bbaf57a6ac9d1aa5422/build/docs/rust.rst#27
> update gkrust-shared on local build

- crates/scope/src/builder.rs
- crates/scope/src/pass.rs
- crates/stencil/src/script.rs
`ImmutableScriptFlagsEnum::FunctionHasNewTargetBinding` must be set for lazy function if it contains `new.target`.
jsparagus doesn't support `new.target`, but the fallback happens only when delazifying, and the compilation of the enclosing script finishes successfully, and not-setting the flag causes wrong delazification.
> Handle new.target (fixed #660)

- Cargo.lock
- crates/driver/Cargo.toml
- crates/driver/src/demo.rs
So far this removes `rustyline` dependency, and regex dependency from `env_logger`.
regex is still in dependency from `criterion` tho.
> Remove rustyline, and env_logger default feature

- crates/emitter/src/emitter.rs
- crates/stencil/src/copy/Opcodes.h
- crates/stencil/src/opcode.rs
https://bugzilla.mozilla.org/show_bug.cgi?id=1781061 added `JSOp::CallContentIter`.
It's mix of `JSOp::CallContent` and `JSOp::CallIter`, and it's used only in self-hosted JS,
and jsparagus doesn't use it.
> Update opcode for bug 1781061
