.gitignore
I don't know if this is necessary yet?
=> add example_pgen.rs to .gitignore

rust/emitter/src/emitter.rs
Followup for https://github.com/jorendorff/jsparagus/pull/33
=> Add derive(Clone, Debug) to EmitError

rust/parser/src/lexer.rs
This is necessary before fixing https://github.com/mozilla-spidermonkey/jsparagus/issues/78
maybe we can use the same naming convention for `finish_without_push` (so, `finish_without_pushing_current_ascii_char` ?) for clarity.
=> Exclude extra backslash from escape sequence (fixes #81)

rust/parser/src/lexer.rs
Moved the unicode escape sequence in string to separate method to share it with that in identifier,
and also both now support braced one as well.
=> Handle UnicodeEscapeSequence in Identifier (fixes #78)

rust/Cargo.lock, rust/emitter/Cargo.toml, rust/emitter/src/ast_emitter.rs, rust/emitter/src/emitter.rs
This is a first go at this, to make sure I am on the right track.
The forward jumps are very basic, I am not checking yet if the jump target is a valid jump target.
=> Implement short circuit operators and basic forward jumps. (fixes #57)

rust/parser/src/lexer.rs
if escape sequence is contained in the text, `AutoCow.value` is `Some(...)` to hold the different text than the source.
so that can be used as the condition here to check if the escape sequence was contained.
and if so, the `TerminalId` should always be `Name`
=> Do not check keyword if matching literal sequence contains escape sequence (fixes #93)

.github/workflows/rust.yml
I wonder if "don't push to production on Friday" applies to setting up CIs 🤔 
Fixes #96
=> Set up CI (fixes #96)

rust/parser/src/lexer.rs
=> Report Err(NotImplemented) for UnicodeEscapeSequences in the surrogate range.

rust/emitter/src/ast_emitter.rs, rust/interpreter/src/evaluate.rs, rust/interpreter/src/value.rs
I wanted to do some more testing with the bytecode interpreter and we
seem to not support any conditional expression yet. (OK and/or)
I haven't tested this with SpiderMonkey's interpreter.
=> Implement conditional expressions

rust/ast/ast.json, rust/ast/src/source_location_accessor_generated.rs, rust/ast/src/types_generated.rs, rust/ast/src/visit_generated.rs, rust/emitter/src/ast_emitter.rs, rust/generated_parser/src/ast_builder.rs, rust/generated_parser/src/stack_value_generated.rs
I tried to make the goto/jumps as clear as possible, but the optional `else` branch makes it a bit difficult. I am open to suggestions. Because we don't implement blocks yet, if statement must look like `if (true) 1; else 2;`.
=> implement if statement

rust/Cargo.lock, rust/ast/ast.json, rust/ast/src/source_location_accessor_generated.rs, rust/ast/src/types_generated.rs, rust/ast/src/visit_generated.rs, rust/emitter/src/ast_emitter.rs, rust/generated_parser/src/ast_builder.rs, rust/generated_parser/src/stack_value_generated.rs, rust/interpreter/Cargo.toml, rust/interpreter/src/lib.rs, rust/interpreter/src/tests.rs
We should wait on landing #171 and rebase. We can't auto derive PartialEq for JSValue, so I decided to use match statements and unboxing the result for now.
=> Interpreter Tests

rust/emitter/src/emitter.rs, rust/emitter/src/opcode.rs
There's corresponding change on rust-frontend
I'll open it after https://github.com/mozilla-spidermonkey/rust-frontend/pull/27
=> Track JOF_TYPESET (fixes #191)

rust/driver/src/demo.rs, rust/emitter/src/ast_emitter.rs, rust/emitter/src/emitter.rs, rust/emitter/src/lib.rs, rust/interpreter/src/tests.rs, rust/parser/src/lib.rs, rust/parser/src/tests.rs
rust-frontend needs the corresponding fix to pass options
=> add EmitOptions and emit SetRval/Pop depending on it (fixes #196)

js_parser/es-simplified.esgrammar, jsparagus/emit/rust.py, rust/ast/ast.json, rust/emitter/src/ast_emitter.rs, rust/generated_parser/src/ast_builder.rs, rust/parser/src/lexer.rs
Depents on #164, fix #140
This works... but I don't think it is an ideal solution. I am not convinced by the extra things i did to make `?. ...` work
=> fix #140 - implement optional chaining in parser and lexer 

.github/workflows/rust.yml, .gitignore, Makefile
I am not sure this is exactly what needs to happen, its just my understanding of what was in the issue
I tested both our pre-existing version (from the initial push for PR #118) and this one. They  both work for making and running the checks on the codebase, but the old way might have been more fragile.
=> fix #195 - create make init

rust/emitter/src/ast_emitter.rs
Fixes #227. No new failures in tests.
=> Implement `new` expression

rust/emitter/src/ast_emitter.rs
=> Implement throw statement

CODE_OF_CONDUCT.md
Small change to help with contributions
=> fixes 249 - add code of conduct

rust/ast/generate_ast.py
First one just removed PostfixPass.
The second one adds visitor methods for enum variants, in the following format:
```
pub trait Pass<'alloc> {
fn visit_argument(&mut self, ast: &mut Argument<'alloc>) {
self.enter_argument(ast);
match ast {
Argument::SpreadElement(ast) => {
self.visit_enum_argument_variant_spread_element(ast)
}
Argument::Expression(ast) => {
self.visit_enum_argument_variant_expression(ast)
}
}
self.leave_argument(ast);
}
...
fn visit_enum_argument_variant_spread_element(
&mut self,
ast: &mut arena::Box<'alloc, Expression<'alloc>>,
) {
self.enter_enum_argument_variant_spread_element(ast);
self.visit_expression(ast);
self.leave_enum_argument_variant_spread_element(ast);
}
fn enter_enum_argument_variant_spread_element(
&mut self,
ast: &mut arena::Box<'alloc, …
```
=> Add visitor methods for each enum variant (fixes #241, fixes #240)

LICENSE, LICENSE-APACHE-2.0, LICENSE-MIT
Based on the suggestion I made in the issue
=> add license (fixes #109)

.github/workflows/ci-generated.yml
I noticed the ci, once it was running against master, was not working. This should fix that.
=> fix generated workflow file for master

crates/emitter/src/ast_emitter.rs, crates/emitter/src/emitter.rs, crates/emitter/src/forward_jump_emitter.rs, crates/emitter/src/lib.rs
This is to get early feedback.If it looks good, I will implement for the other forward jumps.
=> Implement a safer api for forward jumps (fixes #231)

crates/emitter/src/ast_emitter.rs
This was making `emit_expression` difficult to read.
=> Extract MemberExpression to a new function.

crates/emitter/src/ast_emitter.rs
jumping over else branch should be `Goto`
=> Fix if-else (fixs #373)

crates/ast/ast.json, crates/emitter/src/ast_emitter.rs, crates/generated_parser/src/ast_builder.rs
also added `NumericLiteral`, to share it between literal and properties.
=> Add StaticNumericPropertyName and use InitElem for it (fixes #370)

crates/driver/src/demo.rs, crates/interpreter/src/evaluate.rs, crates/interpreter/src/lib.rs, crates/interpreter/src/object.rs
- Use same global for multiple lines in REPL
- DefVar
- Error for not defined vars
=> Interpreter improvements

crates/structured/src/lib.rs
This fix the test cases of the newly introduced structured crate.
=> Fix structured crate test cases.

.metrics/fuzzbug_count_badge.py, .metrics/fuzzbug_date_badge.py, .metrics/not_implemented_count.py, crates/ast/generate_ast.py, js_parser/extract_es_grammar.py, jsparagus/actions.py, jsparagus/emit/python.py, jsparagus/emit/rust.py, jsparagus/extension.py, jsparagus/gen.py, jsparagus/grammar.py, jsparagus/parse_pgen.py, jsparagus/parse_pgen_generated.py, jsparagus/runtime.py, jsparagus/types.py, jsparagus/utils.py, tests/test.py
Fixes #388. After this there are still two warnings, which I'll file as seprate issues.
=> Flake8 fixups

crates/parser/src/parser.rs, crates/parser/src/simulator.rs, jsparagus/emit/python.py, jsparagus/emit/rust.py, jsparagus/runtime.py
This change should fix the issue #431.
This change remove the loop over action function and move the loop within the action function.
=> Epsilon transition to actions, loop within actions states.

crates/ast/ast.json, crates/emitter/src/ast_emitter.rs, crates/emitter/src/control_structures.rs, crates/emitter/src/emitter.rs, crates/generated_parser/src/ast_builder.rs, crates/generated_parser/src/early_errors.rs, crates/generated_parser/src/error.rs
=> Implement labelled statements and breaks; fixes #224

crates/scope/src/pass.rs
Fixed `ScopePass` to call builder methods for getter/setter/arrow functions, that doesn't have either `FormalParameters` or `FunctionBody`.
=> Fix scope analysis for getter/setter and arrow functions (fixes #490)

crates/emitter/src/reference_op_emitter.rs
added `CheckLexical` before `GetLocal`, or `SetLocal` (for case like `{ const x = x = 1; }`).
this doesn't implement `TDZCheckCache`.
=> Implement TDZ check (fixes #511)

jsparagus/aps.py, jsparagus/parse_table.py
This is a clean-up made while working on #430 .
=> Rename is_term_shifted to term_is_shifted like term_is_stacked.

js-quirks.md
I landed a PR from @bakkot today and I'd like to credit him. Also a few minor tweaks.
=> js-quirks.md: more minor fixes

crates/emitter/src/emitter.rs, crates/stencil/src/copy/FunctionFlags.h, crates/stencil/src/copy/Opcodes.h, crates/stencil/src/copy/Symbol.h, crates/stencil/src/opcode.rs
The result of update_stencil.py with latest m-c.
=> Replace JSOp::ToId wit JSOp::ToPropertyKey (fixes #549)

crates/emitter/src/ast_emitter.rs, crates/scope/src/builder.rs, crates/scope/src/free_name_tracker.rs, crates/stencil/src/function.rs, crates/stencil/src/scope.rs, crates/stencil/src/script.rs
Added code to handle the following fields of function stencil:
* nargs
* ImmutableScriptFlags
=> Prepare function stencil fields

src/bin/smoosh_tools.rs
This change updates smoosh_tools such that we can prepend the file pointed by
the `MOZCONFIG` environment variable to the content provided by jsparagus.
This is useful to add new mozconfig options without having to maintain
unpublished changes to jsparagus.
I personally use this system to add dynamically generated options, such as the location of the compiler to be used:
```
mk_add_options AUTOCONF=/nix/store/zywmmqlmrnjfgbh2rwc8ggn0m6qkybqx-autoconf-2.13/bin/autoconf
ac_add_options --with-libclang-path=/nix/store/8wkmipzrvnizzz8gr5is13pmzgcini0v-clang-7.1.0-lib/lib
ac_add_options --with-clang-path=/nix/store/66rz5k5z8ly8wvh12zvjkkdiih9rlav4-clang-wrapper-7.1.0/bin/cc
export BINDGEN_CFLAGS="-cxx-isystem /nix/store/lh2sslfz4l6mac9xgwyy155hq3ab8y8x-gcc-9.3.0/include/c++/9.3.0 -isystem …
```
=> Add --concat-mozconfig to prepend options to the mozconfig.

src/bin/smoosh_tools.rs
Just realized that shell and test doesn't use --smoosh option :P
=> Pass --smoosh to mach run and test

jsparagus/emit/rust.py
This is a cosmetic change which might also as well help Rust speed at compiling the generated code.
=> Improve filter states match

jsparagus/actions.py, jsparagus/parse_table.py, jsparagus/utils.py
This pull-request should fix issue #601 .
=> Fix folding causing inconsistencies

crates/emitter/src/ast_emitter.rs, crates/emitter/src/emitter_scope.rs, crates/emitter/src/function_declaration_emitter.rs, crates/emitter/src/reference_op_emitter.rs, crates/scope/src/builder.rs, crates/stencil/src/scope.rs
Please see each commit message
=> Fix scope and script flags handling for functions

benchmarks/compare-spidermonkey-parsers.js, src/bin/smoosh_tools.rs
Small set of patches to improve benchmark in terms of code, and output and for profiling.
=> Improve bench output for machine and humans

crates/generated_parser/src/ast_builder.rs, crates/generated_parser/src/early_error_checker.rs
remaining patches from https://github.com/mozilla-spidermonkey/jsparagus/pull/612
we got agreement to go with this, and it's already r+ed in https://github.com/mozilla-spidermonkey/jsparagus/pull/612
so I'll merge this after test
=> Reject private identifier and super

crates/stencil/src/copy/Opcodes.h, crates/stencil/src/opcode.rs
https://bugzilla.mozilla.org/show_bug.cgi?id=1656351
https://hg.mozilla.org/mozilla-central/rev/f25c329fad71e0c909ee2131bb2cdb13e6f0eba5
=> Update opcode for bug 1656351

crates/emitter/src/emitter.rs, crates/stencil/src/copy/Opcodes.h, crates/stencil/src/opcode.rs
https://hg.mozilla.org/integration/autoland/rev/6567d54b63c8
https://bugzilla.mozilla.org/show_bug.cgi?id=1655465
(NOTE: this patch isn't yet merged)
=> Update opcode for bug 1655465

crates/emitter/src/emitter.rs, crates/stencil/src/copy/Opcodes.h, crates/stencil/src/opcode.rs
for https://hg.mozilla.org/mozilla-central/rev/22e3020fa080afeaa79292e085aa4d7346a6f9ec
will be vendored in https://bugzilla.mozilla.org/show_bug.cgi?id=1659304
=> Update opcode for bug 1435826

crates/emitter/src/emitter.rs, crates/stencil/src/copy/Opcodes.h, crates/stencil/src/copy/ThrowMsgKind.h, crates/stencil/src/opcode.rs
https://bugzilla.mozilla.org/show_bug.cgi?id=1723155 updated Opcode (new opcode, no other change, just need to import it)
will be vendored in https://bugzilla.mozilla.org/show_bug.cgi?id=1725086
=> Update opcode for bug 1723155

crates/stencil/src/copy/Opcodes.h, crates/stencil/src/opcode.rs
https://bugzilla.mozilla.org/show_bug.cgi?id=1742142
=> Update opcode for bug 1742142

crates/ast/src/associated_data.rs, crates/emitter/src/emitter.rs, crates/scope/src/builder.rs, crates/stencil/src/copy/Opcodes.h, crates/stencil/src/opcode.rs, src/bin/smoosh_tools.rs
https://bugzilla.mozilla.org/show_bug.cgi?id=1760605 removed `JSOp::FunApply`
=> Update opcode for bug 1760605

crates/emitter/src/emitter.rs, crates/stencil/src/copy/Opcodes.h, crates/stencil/src/opcode.rs
https://bugzilla.mozilla.org/show_bug.cgi?id=1760989 removed `JSOp::FunCall`
=> Update opcode for bug 1760989
